# Copyright (C) 2021-2022  Ambassador Labs
#
# SPDX-License-Identifier: Apache-2.0

name: Quality Assurance
on:
  - push
  - pull_request
jobs:
  check:
    name: "${{ github.event_name }} / check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17.0'
      - uses: actions/setup-python@v2
        with:
          python-version: '~3.9.9'
      - name: Show environment info
        run: |
          set -x
          go version
          python --version
          python3 --version
          pip --version
          pip3 --version
      - run: make check
      - name: Report test coverage to coveralls.io
        if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/master' }}
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make tools/bin/goveralls &&
          tools/bin/goveralls -coverprofile=ocibuild.cov -service=github
  lint:
    name: "${{ github.event_name }} / lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17.0'
      - run: make lint
  generate:
    name: "${{ github.event_name }} / generate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17.0'
      - run: make generate
      - name: "Dirty git Check"
        shell: bash
        run: |
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            PAGER= git diff --cached
            exit 1
          fi
  pass:
    name: "${{ github.event_name }} / pass"
    runs-on: ubuntu-latest
    needs:
      - check
      - lint
      - generate
    steps:
      - name: No-Op
        if: ${{ false }}
        run: "echo Pass"
